### ISSUE TITLE
Export to Spine Issue

### ISSUE THREAD

**Issue by crazygrunt** [RampantDespair/Aseprite-Extension#2]
Hello!

I have been trying to use your Despair Extension. When I export the layers from Aseprite it exports them all, but once imported to Spine it seems like it knows the positioning, but it does not show up. I haven't touched this software in quite a while, so it's probably user error here, but I cannot figure out what is wrong.

Here is a screenshot from in Spine:
![1714291316-515115-image](https://github.com/RampantDespair/Aseprite-Extension/assets/3103723/e59d227a-fd8c-4a64-bd9c-05704ad4c470)

Here is the json output:
{ "skeleton": { "images": "./images/" }, "bones": [ { "name": "root" } ], "slots": [ { "name": "slot", "bone": "root", "attachment": "slot" } ], "skins": { "default": { "slot": { "Mage-001-default-Torso": { "x": -3.00, "y": -5.00, "width": 34, "height": 18 } }, "slot": { "Mage-001-default-Right_leg": { "x": -9.00, "y": -15.00, "width": 14, "height": 14 } }, "slot": { "Mage-001-default-Right_foot": { "x": -7.00, "y": -24.00, "width": 10, "height": 8 } }, "slot": { "Mage-001-default-Right_arm": { "x": -14.00, "y": -7.00, "width": 4, "height": 10 } }, "slot": { "Mage-001-default-Left_leg": { "x": 6.00, "y": -15.00, "width": 16, "height": 14 } }, "slot": { "Mage-001-default-Left_foot": { "x": 5.00, "y": -24.00, "width": 10, "height": 8 } }, "slot": { "Mage-001-default-Left_arm": { "x": 12.00, "y": -7.00, "width": 4, "height": 10 } }, "slot": { "Mage-001-default-Cloak": { "x": 18.00, "y": -8.00, "width": 28, "height": 32 } }, "slot": { "Mage-001-default-Head": { "x": 3.00, "y": 14.00, "width": 50, "height": 36 } }} }, "animations": { "animation": {} }}

JSON Data:
![1714291519-572507-image](https://github.com/RampantDespair/Aseprite-Extension/assets/3103723/4f18aa33-3cef-4d3d-95a0-4bc9eb59bbd3)}

Thank you.

Edit:

Aseprite Project Hierarchy:
![image](https://github.com/RampantDespair/Aseprite-Extension/assets/3103723/9a7097b6-dcb3-4cb8-a729-5823ac107230)

Local Config:

configSelect=local
outputSubdirectory=images
outputGroupsAsDirectories=true
spriteSheetExport=true
spriteSheetNameTrim=true
spriteSheetFileNameFormat={spritename}-{layergroup}-{layername}
spriteSheetFileFormat=png
spriteSheetTrim=true
spineExport=true
spineSetStaticSlot=true
spineStaticSlotName=slot
spineSetRootPostion=true
spineRootPostionMethod=center
spineRootPostionX=0
spineRootPostionY=0
spineSetImagesPath=true
spineImagesPath=images
spineGroupsAsSkins=true
spineSkinNameFormat=weapon-{layergroup}
spineSeparateSlotSkin=true
spineSlotNameFormat={layernameprefix}
spineSkinAttachmentFormat={layernameprefix}-{layernamesuffix}
spineLayerNameSeparator=-

**Comment by RampantDespair** [comment]
@crazygrunt 
Hey there,
Try disabling (`spineSetStaticSlot` & `spineGroupsAsSkins`) or replace the contents of your local config with this:
```
configSelect=local
outputSubdirectory=images
outputGroupsAsDirectories=true
spriteSheetExport=true
spriteSheetNameTrim=true
spriteSheetFileNameFormat={spritename}-{layergroup}-{layername}
spriteSheetFileFormat=png
spriteSheetTrim=true
spineExport=true
spineSetStaticSlot=false
spineStaticSlotName=slot
spineSetRootPostion=true
spineRootPostionMethod=center
spineRootPostionX=0
spineRootPostionY=0
spineSetImagesPath=true
spineImagesPath=images
spineGroupsAsSkins=false
spineSkinNameFormat=weapon-{layergroup}
spineSeparateSlotSkin=true
spineSlotNameFormat={layernameprefix}
spineSkinAttachmentFormat={layernameprefix}-{layernamesuffix}
spineLayerNameSeparator=-
```

**Comment by crazygrunt** [comment]
This works to show the image. However it seems they are not all separated out by pieces, but instead all one piece. Not sure what I did wrong here.

![image](https://github.com/RampantDespair/Aseprite-Extension/assets/3103723/448886ea-3088-4201-8bbe-146abc6282f3)

**Comment by RampantDespair** [comment]
@crazygrunt
The extension I made doesn't have a setting to combine layers together, so I am slightly confused as to how you got that in your output. 
I just tried it right now with
```
configSelect=global
outputSubdirectory=images
outputGroupsAsDirectories=false
spriteSheetExport=true
spriteSheetNameTrim=true
spriteSheetFileNameFormat={spritename}-{layergroup}-{layername}
spriteSheetFileFormat=png
spriteSheetTrim=true
spineExport=true
spineSetStaticSlot=true
spineStaticSlotName=slot
spineSetRootPostion=true
spineRootPostionMethod=center
spineRootPostionX=0
spineRootPostionY=0
spineSetImagesPath=true
spineImagesPath=images
spineSkins=false
spineSkinsMode=groups
spineSkinNameFormat=weapon-{layergroup}
spineSeparateSlotSkin=true
spineSlotNameFormat={layernameprefix}
spineSkinAttachmentFormat={layernameprefix}-{layernamesuffix}
spineLayerNameSeparator=-
```
And it works.
Are you sure you are doing Despair Extension > Export and not just Export?

**Comment by crazygrunt** [comment]
Got it working. I think it was mostly lack of understanding on my part. I needed to provide separate slots for the attachments in Spine.

Thanks for all the help!

![image](https://github.com/RampantDespair/Aseprite-Extension/assets/3103723/e5c9df27-46e8-4480-96df-c4913b47c4db)
